---
pipeline: default
name: default
steps:
- name: build
  image: docker
  command:
    - docker build -t nodeintegration/bevenv:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
- name: test
  image: docker
  command:
    - docker run -t nodeintegration/bevenv:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER} echo "yay"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

