---
pipeline: default
name: default
steps:
- name: build
  image: docker
  commands:
  - docker build -t nodeintegration/bevenv:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
- name: test
  image: docker
  commands:
  - docker ps
  - docker images | grep nodeintegration | grep bevenv
  - docker run nodeintegration/bevenv:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER} echo "yay"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
